export const GET_CHARACTERS = 'GET_CHARACTERS';
export const LIKE_CHARACTER = 'LIKE_CHARACTER';
export const DISLIKE_CHARACTER = 'DISLIKE_CHARACTER';
export const GET_DUDE = 'GET_DUDE';
export const ADD_CHARACTERS = 'ADD_CHARACTERS';
